In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [1]:
cd ..

/home/chiroptera/workspace/QCThesis


In [240]:
import MyML.graph.mst
reload(MyML.graph.mst)
from MyML.graph.mst import boruvkaMinhoSeq, boruvkaMinhoSeqForest

In [249]:
dest2 = np.array([3, 1, 2, 3, 0, 2, 0, 1, 0, 1, 7, 5, 6, 4, 6, 5, 4, 4], dtype = np.int32)
weight2 = np.array([4, 2, 5, 3, 2, 4, 5, 4, 4, 3, 2, 4, 8, 4, 3, 3, 8, 2], dtype = np.float32)
fe2 = np.array([0, 3, 6, 8, 10, 13, 15, 17], dtype = np.int32)
od2 = np.array([3, 3, 2, 2, 3, 2, 2, 1], dtype = np.int32)

In [250]:
mst_solver = boruvkaMinhoSeqForest(dest2, weight2, fe2, od2)

In [243]:
mst_solver.fit()

array([ 4,  7,  9, 15, 17, 13,  3], dtype=int32)

In [190]:
mst_solver = boruvkaMinhoSeq(dest2, weight2, fe2, od2)

In [261]:
print mst_solver.n_components
print mst_solver.n_mst

3
2


In [262]:
#%%debug
mst_solver.findMinEdge()
mst_solver.vertex_minedge

array([-1,  0,  2], dtype=int32)

In [263]:
mst_solver.removeMirrored()
mst_solver.vertex_minedge

array([-1, -1,  2], dtype=int32)

In [265]:
mst_solver.initColors()
print mst_solver.colors

[0 1 1]


In [266]:
while(not mst_solver.converged):
    mst_solver.propagateColors()
print mst_solver.colors

[0 1 1]


In [267]:
mst_solver.createNewVertexID()
print mst_solver.new_vertex

[0 1 2]


In [268]:
mst_solver.countNewVertex()
print mst_solver.new_first_edge
print mst_solver.new_outDegree

[0 0]
[0 0]


In [269]:
mst_solver.removeMST()

In [271]:
mst_solver.n_mst

3

In [276]:
print mst_solver.edge_id
print mst_solver.dest
print mst_solver.weight
print mst_solver.firstEdge
print mst_solver.outDegree

[]
[]
[]
[0 0]
[0 0]


In [273]:
mst_solver.assignInsert()
print mst_solver.edge_id
print mst_solver.dest
print mst_solver.weight
print mst_solver.firstEdge
print mst_solver.outDegree

AttributeError: boruvkaMinhoSeqForest instance has no attribute 'new_first_edge'

In [275]:
mst_solver.n_components

2

In [ ]:
mst_solver.fit()